apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: fluxforge
data:
  nginx.conf: |
    events {}
    http {
      upstream fluxforge_control {
        server fluxforge-control:8080;
      }
      
      # Strict TLS
      ssl_protocols TLSv1.2 TLSv1.3;
      ssl_ciphers HIGH:!aNULL:!MD5;
      ssl_prefer_server_ciphers on;
      
      server {
        listen 8080;
        server_name localhost;
        return 301 https://$host:8443$request_uri;
      }
      
      server {
        listen 443 ssl;
        server_name localhost;
        
        ssl_certificate /etc/nginx/certs/fluxforge.crt;
        ssl_certificate_key /etc/nginx/certs/fluxforge.key;
        
        location / {
          proxy_pass http://fluxforge_control;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto https;
        }
      }
    }
